# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Yichen's Blog
email: yzhao@trainup.com
description: My first blog on Github
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "http://wudiguabi.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  wudiguabi


# Build settings
markdown: kramdown
highlighter: rouge
